title: Greenjenny
baseurl: ""
url: "https://greenjenny.com"

markdown: redcarpet
plugins:
  - jekyll-feed
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  
